CREATE TABLE IF NOT EXISTS tasks (
    id SERIAL PRIMARY KEY,
    state TEXT NOT NULL DEFAULT 'PENDING',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    process_started_at TIMESTAMP,
    process_ended_at TIMESTAMP
);
